### ISSUE TITLE
get_container_info_for_scan() prints some error

### ISSUE THREAD

**Issue by johannesmayer** [ckolbPTB/OpenHeart#15]
The error is:

`openheart-app-1  | 2023-03-17 13:01:04,914 ERROR openheart Thread-72 [xnat.py:217 - get_container_info_for_scan() ]: raw-in not found in container json`

However, the reconstructions are still performed correctly and the snapshots are picked up by the webpage.

**Comment by ckolbPTB** [comment]
Fixed with PR #18
